<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            ['id' => 1, 'name' => 'Alberti', 'province_id' => 1],
            ['id' => 2, 'name' => 'Azul', 'province_id' => 1],
            ['id' => 3, 'name' => 'Capital', 'province_id' => 2],
            ['id' => 4, 'name' => 'Guaymallén', 'province_id' => 3],
            ['id' => 5, 'name' => 'Daireaux', 'province_id' => 1],
            ['id' => 6, 'name' => 'General Paz', 'province_id' => 1],
            ['id' => 7, 'name' => 'Rojas', 'province_id' => 1],
            ['id' => 8, 'name' => 'Tapalqué', 'province_id' => 1],
            ['id' => 9, 'name' => 'Tres Arroyos', 'province_id' => 1],
            ['id' => 10, 'name' => 'Chacabuco', 'province_id' => 4],
            ['id' => 11, 'name' => 'Sarmiento', 'province_id' => 5],
            ['id' => 12, 'name' => 'Matacos', 'province_id' => 6],
            ['id' => 13, 'name' => 'Susques', 'province_id' => 7],
            ['id' => 14, 'name' => 'Pehuenches', 'province_id' => 8],
            ['id' => 15, 'name' => 'La Poma', 'province_id' => 9],
            ['id' => 16, 'name' => 'Belgrano', 'province_id' => 10],
            ['id' => 17, 'name' => 'Almirante Brown', 'province_id' => 1],
            ['id' => 18, 'name' => 'Avellaneda', 'province_id' => 1],
            ['id' => 19, 'name' => 'Bahía Blanca', 'province_id' => 1],
            ['id' => 20, 'name' => 'Berazategui', 'province_id' => 1],
            ['id' => 21, 'name' => 'Berisso', 'province_id' => 1],
            ['id' => 22, 'name' => 'Cañuelas', 'province_id' => 1],
            ['id' => 23, 'name' => 'Coronel de Marina Leonardo Rosales', 'province_id' => 1],
            ['id' => 24, 'name' => 'Chascomús', 'province_id' => 1],
            ['id' => 25, 'name' => 'Ensenada', 'province_id' => 1],
            ['id' => 26, 'name' => 'Escobar', 'province_id' => 1],
            ['id' => 27, 'name' => 'Esteban Echeverría', 'province_id' => 1],
            ['id' => 28, 'name' => 'Exaltación de la Cruz', 'province_id' => 1],
            ['id' => 29, 'name' => 'Morón', 'province_id' => 1],
            ['id' => 30, 'name' => 'Ezeiza', 'province_id' => 1],
            ['id' => 31, 'name' => 'Florencio Varela', 'province_id' => 1],
            ['id' => 32, 'name' => 'General Juan Madariaga', 'province_id' => 1],
            ['id' => 33, 'name' => 'General Pueyrredón', 'province_id' => 1],
            ['id' => 34, 'name' => 'La Plata', 'province_id' => 1],
            ['id' => 35, 'name' => 'General Rodríguez', 'province_id' => 1],
            ['id' => 36, 'name' => 'General San Martín', 'province_id' => 1],
            ['id' => 37, 'name' => 'Hurlingham', 'province_id' => 1],
            ['id' => 38, 'name' => 'Ituzaingó', 'province_id' => 1],
            ['id' => 39, 'name' => 'José C. Paz', 'province_id' => 1],
            ['id' => 40, 'name' => 'La Costa', 'province_id' => 1],
            ['id' => 41, 'name' => 'La Matanza', 'province_id' => 1],
            ['id' => 42, 'name' => 'Santa María', 'province_id' => 2],
            ['id' => 43, 'name' => 'Lanús', 'province_id' => 1],
            ['id' => 44, 'name' => 'Lomas de Zamora', 'province_id' => 1],
            ['id' => 45, 'name' => 'Luján', 'province_id' => 1],
            ['id' => 46, 'name' => 'Malvinas Argentinas', 'province_id' => 1],
            ['id' => 47, 'name' => 'Mar Chiquita', 'province_id' => 1],
            ['id' => 48, 'name' => 'Marcos Paz', 'province_id' => 1],
            ['id' => 49, 'name' => 'Merlo', 'province_id' => 1],
            ['id' => 50, 'name' => 'Moreno', 'province_id' => 1],
            ['id' => 51, 'name' => 'Necochea', 'province_id' => 1],
            ['id' => 52, 'name' => 'Olavarría', 'province_id' => 1],
            ['id' => 53, 'name' => 'Pilar', 'province_id' => 1],
            ['id' => 54, 'name' => 'Pinamar', 'province_id' => 1],
            ['id' => 55, 'name' => 'Presidente Perón', 'province_id' => 1],
            ['id' => 56, 'name' => 'Quilmes', 'province_id' => 1],
            ['id' => 57, 'name' => 'San Fernando', 'province_id' => 1],
            ['id' => 58, 'name' => 'San Isidro', 'province_id' => 1],
            ['id' => 59, 'name' => 'San Miguel', 'province_id' => 1],
            ['id' => 60, 'name' => 'San Nicolás', 'province_id' => 1],
            ['id' => 61, 'name' => 'San Vicente', 'province_id' => 1],
            ['id' => 62, 'name' => 'Tigre', 'province_id' => 1],
            ['id' => 63, 'name' => 'Tres de Febrero', 'province_id' => 1],
            ['id' => 64, 'name' => 'Vicente López', 'province_id' => 1],
            ['id' => 65, 'name' => 'Villa Gesell', 'province_id' => 1],
            ['id' => 66, 'name' => 'Zárate', 'province_id' => 1],
            ['id' => 67, 'name' => 'Andalgalá', 'province_id' => 11],
            ['id' => 68, 'name' => 'Capayán', 'province_id' => 11],
            ['id' => 69, 'name' => 'Fray Mamerto Esquiú', 'province_id' => 11],
            ['id' => 70, 'name' => 'Santa María', 'province_id' => 11],
            ['id' => 71, 'name' => 'Tinogasta', 'province_id' => 11],
            ['id' => 72, 'name' => 'Valle Viejo', 'province_id' => 11],
            ['id' => 73, 'name' => 'Calamuchita', 'province_id' => 2],
            ['id' => 74, 'name' => 'Colón', 'province_id' => 2],
            ['id' => 75, 'name' => 'Punilla', 'province_id' => 2],
            ['id' => 76, 'name' => 'San Javier', 'province_id' => 2],
            ['id' => 77, 'name' => 'Escalante', 'province_id' => 5],
            ['id' => 78, 'name' => 'Colón', 'province_id' => 12],
            ['id' => 79, 'name' => 'Concordia', 'province_id' => 12],
            ['id' => 80, 'name' => 'Diamante', 'province_id' => 12],
            ['id' => 81, 'name' => 'Paraná', 'province_id' => 12],
            ['id' => 82, 'name' => 'Chilecito', 'province_id' => 13],
            ['id' => 83, 'name' => 'Patiño', 'province_id' => 6],
            ['id' => 84, 'name' => 'El Carmen', 'province_id' => 7],
            ['id' => 85, 'name' => 'Dr. Manuel Belgrano', 'province_id' => 7],
            ['id' => 86, 'name' => 'Ledesma', 'province_id' => 7],
            ['id' => 87, 'name' => 'Palpalá', 'province_id' => 7],
            ['id' => 88, 'name' => 'Tilcara', 'province_id' => 7],
            ['id' => 89, 'name' => 'Yavi', 'province_id' => 7],
            ['id' => 90, 'name' => 'Arauco', 'province_id' => 13],
            ['id' => 91, 'name' => 'Coronel Felipe Varela', 'province_id' => 13],
            ['id' => 92, 'name' => 'San Blas de los Sauces', 'province_id' => 13],
            ['id' => 93, 'name' => 'Capital', 'province_id' => 3],
            ['id' => 94, 'name' => 'Godoy Cruz', 'province_id' => 3],
            ['id' => 95, 'name' => 'Las Heras', 'province_id' => 3],
            ['id' => 96, 'name' => 'Luján de Cuyo', 'province_id' => 3],
            ['id' => 97, 'name' => 'Maipú', 'province_id' => 3],
            ['id' => 98, 'name' => 'Rivadavia', 'province_id' => 3],
            ['id' => 99, 'name' => 'San Martín', 'province_id' => 3],
            ['id' => 100, 'name' => 'San Rafael', 'province_id' => 3],
            ['id' => 101, 'name' => 'Tupungato', 'province_id' => 3],
            ['id' => 102, 'name' => 'Cainguás', 'province_id' => 14],
            ['id' => 103, 'name' => 'Zapala', 'province_id' => 8],
            ['id' => 104, 'name' => 'Adolfo Alsina', 'province_id' => 1],
            ['id' => 105, 'name' => 'Bariloche', 'province_id' => 15],
            ['id' => 106, 'name' => 'Famaillá', 'province_id' => 16],
            ['id' => 107, 'name' => 'General Roca', 'province_id' => 15],
            ['id' => 108, 'name' => 'Capital', 'province_id' => 9],
            ['id' => 109, 'name' => 'Cerrillos', 'province_id' => 9],
            ['id' => 110, 'name' => 'General José de San Martín', 'province_id' => 9],
            ['id' => 111, 'name' => 'Juan Martín Pueyrredón', 'province_id' => 17],
            ['id' => 112, 'name' => 'Orán', 'province_id' => 9],
            ['id' => 113, 'name' => 'Angaco', 'province_id' => 18],
            ['id' => 114, 'name' => 'Caucete', 'province_id' => 18],
            ['id' => 115, 'name' => 'Jáchal', 'province_id' => 18],
            ['id' => 116, 'name' => 'Pocito', 'province_id' => 18],
            ['id' => 117, 'name' => 'Rawson', 'province_id' => 18],
            ['id' => 118, 'name' => 'Santa Lucía', 'province_id' => 18],
            ['id' => 119, 'name' => '25 de Mayo', 'province_id' => 18],
            ['id' => 120, 'name' => 'Zonda', 'province_id' => 18],
            ['id' => 121, 'name' => 'General Pedernera', 'province_id' => 17],
            ['id' => 122, 'name' => 'Castellanos', 'province_id' => 10],
            ['id' => 123, 'name' => 'La Capital', 'province_id' => 10],
            ['id' => 124, 'name' => 'Cruz Alta', 'province_id' => 16],
            ['id' => 125, 'name' => 'Lules', 'province_id' => 16],
            ['id' => 126, 'name' => 'Río Chico', 'province_id' => 16],
            ['id' => 127, 'name' => 'Yerba Buena', 'province_id' => 16],
            ['id' => 128, 'name' => 'Islas del Atlántico Sur', 'province_id' => 19],
            ['id' => 129, 'name' => 'Antártida Argentina', 'province_id' => 19],
            ['id' => 130, 'name' => 'Ayacucho', 'province_id' => 1],
            ['id' => 131, 'name' => 'Adolfo Gonzales Chaves', 'province_id' => 1],
            ['id' => 132, 'name' => 'Balcarce', 'province_id' => 1],
            ['id' => 133, 'name' => 'Arrecifes', 'province_id' => 1],
            ['id' => 134, 'name' => 'Baradero', 'province_id' => 1],
            ['id' => 135, 'name' => 'Benito Juárez', 'province_id' => 1],
            ['id' => 136, 'name' => 'Bolívar', 'province_id' => 1],
            ['id' => 137, 'name' => 'Bragado', 'province_id' => 1],
            ['id' => 138, 'name' => 'Brandsen', 'province_id' => 1],
            ['id' => 139, 'name' => 'Campana', 'province_id' => 1],
            ['id' => 140, 'name' => 'Carlos Tejedor', 'province_id' => 1],
            ['id' => 141, 'name' => 'Capitán Sarmiento', 'province_id' => 1],
            ['id' => 142, 'name' => 'Carlos Casares', 'province_id' => 1],
            ['id' => 143, 'name' => 'Carmen de Areco', 'province_id' => 1],
            ['id' => 144, 'name' => 'Castelli', 'province_id' => 1],
            ['id' => 145, 'name' => 'Colón', 'province_id' => 1],
            ['id' => 146, 'name' => 'Coronel Dorrego', 'province_id' => 1],
            ['id' => 147, 'name' => 'Coronel Pringles', 'province_id' => 1],
            ['id' => 148, 'name' => 'Coronel Suárez', 'province_id' => 1],
            ['id' => 149, 'name' => 'Chacabuco', 'province_id' => 1],
            ['id' => 150, 'name' => 'Lezama', 'province_id' => 1],
            ['id' => 151, 'name' => 'Chivilcoy', 'province_id' => 1],
            ['id' => 152, 'name' => 'Dolores', 'province_id' => 1],
            ['id' => 153, 'name' => 'Florentino Ameghino', 'province_id' => 1],
            ['id' => 154, 'name' => 'General Alvarado', 'province_id' => 1],
            ['id' => 155, 'name' => 'General La Madrid', 'province_id' => 1],
            ['id' => 156, 'name' => 'General Belgrano', 'province_id' => 1],
            ['id' => 157, 'name' => 'General Alvear', 'province_id' => 1],
            ['id' => 158, 'name' => 'Guaminí', 'province_id' => 1],
            ['id' => 159, 'name' => 'General Arenales', 'province_id' => 1],
            ['id' => 160, 'name' => 'General Guido', 'province_id' => 1],
            ['id' => 161, 'name' => 'General Las Heras', 'province_id' => 1],
            ['id' => 162, 'name' => 'General Lavalle', 'province_id' => 1],
            ['id' => 163, 'name' => 'General Pinto', 'province_id' => 1],
            ['id' => 164, 'name' => 'General Viamonte', 'province_id' => 1],
            ['id' => 165, 'name' => 'General Villegas', 'province_id' => 1],
            ['id' => 166, 'name' => 'General Villegas', 'province_id' => 2],
            ['id' => 167, 'name' => 'Hipólito Yrigoyen', 'province_id' => 1],
            ['id' => 168, 'name' => 'Junín', 'province_id' => 1],
            ['id' => 169, 'name' => 'Laprida', 'province_id' => 1],
            ['id' => 170, 'name' => 'Las Flores', 'province_id' => 1],
            ['id' => 171, 'name' => 'Leandro N. Alem', 'province_id' => 1],
            ['id' => 172, 'name' => 'Lincoln', 'province_id' => 1],
            ['id' => 173, 'name' => 'Lobería', 'province_id' => 1],
            ['id' => 174, 'name' => 'Lobos', 'province_id' => 1],
            ['id' => 175, 'name' => 'Magdalena', 'province_id' => 1],
            ['id' => 176, 'name' => 'Maipú', 'province_id' => 1],
            ['id' => 177, 'name' => 'Mercedes', 'province_id' => 1],
            ['id' => 178, 'name' => 'Monte', 'province_id' => 1],
            ['id' => 179, 'name' => 'Monte Hermoso', 'province_id' => 1],
            ['id' => 180, 'name' => 'Navarro', 'province_id' => 1],
            ['id' => 181, 'name' => '9 de Julio', 'province_id' => 1],
            ['id' => 182, 'name' => 'Patagones', 'province_id' => 1],
            ['id' => 183, 'name' => 'Pehuajó', 'province_id' => 1],
            ['id' => 184, 'name' => 'Pellegrini', 'province_id' => 1],
            ['id' => 185, 'name' => 'Pergamino', 'province_id' => 1],
            ['id' => 186, 'name' => 'Pila', 'province_id' => 1],
            ['id' => 187, 'name' => 'Puán', 'province_id' => 1],
            ['id' => 188, 'name' => 'Punta Indio', 'province_id' => 1],
            ['id' => 189, 'name' => 'Ramallo', 'province_id' => 1],
            ['id' => 190, 'name' => 'Rauch', 'province_id' => 1],
            ['id' => 191, 'name' => 'Rivadavia', 'province_id' => 1],
            ['id' => 192, 'name' => 'Roque Pérez', 'province_id' => 1],
            ['id' => 193, 'name' => 'San Pedro', 'province_id' => 1],
            ['id' => 194, 'name' => 'Saavedra', 'province_id' => 1],
            ['id' => 195, 'name' => 'Saladillo', 'province_id' => 1],
            ['id' => 196, 'name' => 'Salto', 'province_id' => 1],
            ['id' => 197, 'name' => 'Salliqueló', 'province_id' => 1],
            ['id' => 198, 'name' => 'San Andrés de Giles', 'province_id' => 1],
            ['id' => 199, 'name' => 'San Antonio de Areco', 'province_id' => 1],
            ['id' => 200, 'name' => 'San Cayetano', 'province_id' => 1],
            ['id' => 201, 'name' => 'Suipacha', 'province_id' => 1],
            ['id' => 202, 'name' => 'Tandil', 'province_id' => 1],
            ['id' => 203, 'name' => 'Tordillo', 'province_id' => 1],
            ['id' => 204, 'name' => 'Tornquist', 'province_id' => 1],
            ['id' => 205, 'name' => 'Trenque Lauquen', 'province_id' => 1],
            ['id' => 206, 'name' => 'Tres Lomas', 'province_id' => 1],
            ['id' => 207, 'name' => '25 de Mayo', 'province_id' => 1],
            ['id' => 208, 'name' => 'Villarino', 'province_id' => 1],
            ['id' => 209, 'name' => 'Ambato', 'province_id' => 11],
            ['id' => 210, 'name' => 'Ancasti', 'province_id' => 11],
            ['id' => 211, 'name' => 'Antofagasta de la Sierra', 'province_id' => 11],
            ['id' => 212, 'name' => 'Belén', 'province_id' => 11],
            ['id' => 213, 'name' => 'Capital', 'province_id' => 11],
            ['id' => 214, 'name' => 'El Alto', 'province_id' => 11],
            ['id' => 215, 'name' => 'La Paz', 'province_id' => 11],
            ['id' => 216, 'name' => 'La Paz', 'province_id' => 20],
            ['id' => 217, 'name' => 'Paclín', 'province_id' => 11],
            ['id' => 218, 'name' => 'Pomán', 'province_id' => 11],
            ['id' => 219, 'name' => 'Santa Rosa', 'province_id' => 11],
            ['id' => 220, 'name' => 'Minas', 'province_id' => 2],
            ['id' => 221, 'name' => 'Cruz del Eje', 'province_id' => 2],
            ['id' => 222, 'name' => 'General Roca', 'province_id' => 2],
            ['id' => 223, 'name' => 'General San Martín', 'province_id' => 2],
            ['id' => 224, 'name' => 'Ischilín', 'province_id' => 2],
            ['id' => 225, 'name' => 'Juárez Celman', 'province_id' => 2],
            ['id' => 226, 'name' => 'Marcos Juárez', 'province_id' => 2],
            ['id' => 227, 'name' => 'Pocho', 'province_id' => 2],
            ['id' => 228, 'name' => 'Presidente Roque Sáenz Peña', 'province_id' => 2],
            ['id' => 229, 'name' => 'Río Cuarto', 'province_id' => 2],
            ['id' => 230, 'name' => 'Río Primero', 'province_id' => 2],
            ['id' => 231, 'name' => 'Río Seco', 'province_id' => 2],
            ['id' => 232, 'name' => 'Río Seco', 'province_id' => 20],
            ['id' => 233, 'name' => 'Río Segundo', 'province_id' => 2],
            ['id' => 234, 'name' => 'San Alberto', 'province_id' => 2],
            ['id' => 235, 'name' => 'San Justo', 'province_id' => 2],
            ['id' => 236, 'name' => 'Sobremonte', 'province_id' => 2],
            ['id' => 237, 'name' => 'Totoral', 'province_id' => 2],
            ['id' => 238, 'name' => 'Tercero Arriba', 'province_id' => 2],
            ['id' => 239, 'name' => 'Tulumba', 'province_id' => 2],
            ['id' => 240, 'name' => 'Unión', 'province_id' => 2],
            ['id' => 241, 'name' => 'Bella Vista', 'province_id' => 21],
            ['id' => 242, 'name' => 'Berón de Astrada', 'province_id' => 21],
            ['id' => 243, 'name' => 'Capital', 'province_id' => 21],
            ['id' => 244, 'name' => 'Concepción', 'province_id' => 21],
            ['id' => 245, 'name' => 'Curuzú Cuatiá', 'province_id' => 21],
            ['id' => 246, 'name' => 'Curuzú Cuatiá', 'province_id' => 12],
            ['id' => 247, 'name' => 'Empedrado', 'province_id' => 21],
            ['id' => 248, 'name' => 'Esquina', 'province_id' => 21],
            ['id' => 249, 'name' => 'General Alvear', 'province_id' => 21],
            ['id' => 250, 'name' => 'General Paz', 'province_id' => 21],
            ['id' => 251, 'name' => 'Goya', 'province_id' => 21],
            ['id' => 252, 'name' => 'Itatí', 'province_id' => 21],
            ['id' => 253, 'name' => 'Ituzaingó', 'province_id' => 21],
            ['id' => 254, 'name' => 'Lavalle', 'province_id' => 21],
            ['id' => 255, 'name' => 'Mburucuyá', 'province_id' => 21],
            ['id' => 256, 'name' => 'Mercedes', 'province_id' => 21],
            ['id' => 257, 'name' => 'Monte Caseros', 'province_id' => 21],
            ['id' => 258, 'name' => 'Paso de los Libres', 'province_id' => 21],
            ['id' => 259, 'name' => 'Saladas', 'province_id' => 21],
            ['id' => 260, 'name' => 'San Cosme', 'province_id' => 21],
            ['id' => 261, 'name' => 'San Luis del Palmar', 'province_id' => 21],
            ['id' => 262, 'name' => 'San Martín', 'province_id' => 21],
            ['id' => 263, 'name' => 'San Miguel', 'province_id' => 21],
            ['id' => 264, 'name' => 'Sauce', 'province_id' => 21],
            ['id' => 265, 'name' => 'San Roque', 'province_id' => 21],
            ['id' => 266, 'name' => 'Santo Tomé', 'province_id' => 21],
            ['id' => 267, 'name' => 'Almirante Brown', 'province_id' => 4],
            ['id' => 268, 'name' => 'Bermejo', 'province_id' => 4],
            ['id' => 269, 'name' => 'Comandante Fernández', 'province_id' => 4],
            ['id' => 270, 'name' => '12 de Octubre', 'province_id' => 4],
            ['id' => 271, 'name' => '2 de Abril', 'province_id' => 4],
            ['id' => 272, 'name' => 'Fray Justo Santa María de Oro', 'province_id' => 4],
            ['id' => 273, 'name' => 'General Güemes', 'province_id' => 4],
            ['id' => 274, 'name' => 'General Belgrano', 'province_id' => 4],
            ['id' => 275, 'name' => 'General Donovan', 'province_id' => 4],
            ['id' => 276, 'name' => 'Independencia', 'province_id' => 4],
            ['id' => 277, 'name' => 'Libertad', 'province_id' => 4],
            ['id' => 278, 'name' => 'Libertador General San Martín', 'province_id' => 4],
            ['id' => 279, 'name' => '9 de Julio', 'province_id' => 4],
            ['id' => 280, 'name' => 'Maipú', 'province_id' => 4],
            ['id' => 281, 'name' => 'Mayor Luis J. Fontana', 'province_id' => 4],
            ['id' => 282, 'name' => 'O\'Higgins', 'province_id' => 4],
            ['id' => 283, 'name' => 'Presidencia de la Plaza', 'province_id' => 4],
            ['id' => 284, 'name' => 'Quitilipi', 'province_id' => 4],
            ['id' => 285, 'name' => '1º de Mayo', 'province_id' => 4],
            ['id' => 286, 'name' => 'San Fernando', 'province_id' => 4],
            ['id' => 287, 'name' => 'San Fernando', 'province_id' => 10],
            ['id' => 288, 'name' => 'San Lorenzo', 'province_id' => 4],
            ['id' => 289, 'name' => 'Sargento Cabral', 'province_id' => 4],
            ['id' => 290, 'name' => 'Tapenagá', 'province_id' => 4],
            ['id' => 291, 'name' => '25 de Mayo', 'province_id' => 4],
            ['id' => 292, 'name' => 'Biedma', 'province_id' => 15],
            ['id' => 293, 'name' => 'Biedma', 'province_id' => 5],
            ['id' => 294, 'name' => 'Cushamen', 'province_id' => 5],
            ['id' => 295, 'name' => 'Florentino Ameghino', 'province_id' => 5],
            ['id' => 296, 'name' => 'Futaleufú', 'province_id' => 5],
            ['id' => 297, 'name' => 'Gaiman', 'province_id' => 5],
            ['id' => 298, 'name' => 'Gastre', 'province_id' => 5],
            ['id' => 299, 'name' => 'Languiñeo', 'province_id' => 5],
            ['id' => 300, 'name' => 'Mártires', 'province_id' => 5],
            ['id' => 301, 'name' => 'Paso de Indios', 'province_id' => 5],
            ['id' => 302, 'name' => 'Rawson', 'province_id' => 5],
            ['id' => 303, 'name' => 'Río Senguer', 'province_id' => 5],
            ['id' => 304, 'name' => 'Tehuelches', 'province_id' => 5],
            ['id' => 305, 'name' => 'Telsen', 'province_id' => 5],
            ['id' => 306, 'name' => 'Federación', 'province_id' => 12],
            ['id' => 307, 'name' => 'Federal', 'province_id' => 12],
            ['id' => 308, 'name' => 'Feliciano', 'province_id' => 12],
            ['id' => 309, 'name' => 'Gualeguay', 'province_id' => 12],
            ['id' => 310, 'name' => 'Gualeguaychú', 'province_id' => 12],
            ['id' => 311, 'name' => 'La Paz', 'province_id' => 12],
            ['id' => 312, 'name' => 'Islas del Ibicuy', 'province_id' => 12],
            ['id' => 313, 'name' => 'Nogoyá', 'province_id' => 12],
            ['id' => 314, 'name' => 'San Salvador', 'province_id' => 12],
            ['id' => 315, 'name' => 'Tala', 'province_id' => 12],
            ['id' => 316, 'name' => 'Uruguay', 'province_id' => 12],
            ['id' => 317, 'name' => 'Victoria', 'province_id' => 12],
            ['id' => 318, 'name' => 'Villaguay', 'province_id' => 12],
            ['id' => 319, 'name' => 'Laishi', 'province_id' => 6],
            ['id' => 320, 'name' => 'Bermejo', 'province_id' => 6],
            ['id' => 321, 'name' => 'Formosa', 'province_id' => 6],
            ['id' => 322, 'name' => 'Pilagás', 'province_id' => 6],
            ['id' => 323, 'name' => 'Pirané', 'province_id' => 6],
            ['id' => 324, 'name' => 'Pilcomayo', 'province_id' => 6],
            ['id' => 325, 'name' => 'Ramón Lista', 'province_id' => 6],
            ['id' => 326, 'name' => 'Cochinoca', 'province_id' => 7],
            ['id' => 327, 'name' => 'Humahuaca', 'province_id' => 7],
            ['id' => 328, 'name' => 'Rinconada', 'province_id' => 7],
            ['id' => 329, 'name' => 'San Antonio', 'province_id' => 7],
            ['id' => 330, 'name' => 'San Pedro', 'province_id' => 7],
            ['id' => 331, 'name' => 'Santa Bárbara', 'province_id' => 7],
            ['id' => 332, 'name' => 'Santa Catalina', 'province_id' => 7],
            ['id' => 333, 'name' => 'Tumbaya', 'province_id' => 7],
            ['id' => 334, 'name' => 'Valle Grande', 'province_id' => 7],
            ['id' => 335, 'name' => 'Atreucó', 'province_id' => 22],
            ['id' => 336, 'name' => 'Caleu Caleu', 'province_id' => 22],
            ['id' => 337, 'name' => 'Capital', 'province_id' => 22],
            ['id' => 338, 'name' => 'Catriló', 'province_id' => 22],
            ['id' => 339, 'name' => 'Conhelo', 'province_id' => 22],
            ['id' => 340, 'name' => 'Curacó', 'province_id' => 22],
            ['id' => 341, 'name' => 'Chalileo', 'province_id' => 22],
            ['id' => 342, 'name' => 'Chapaleufú', 'province_id' => 22],
            ['id' => 343, 'name' => 'Chical Co', 'province_id' => 22],
            ['id' => 344, 'name' => 'Guatraché', 'province_id' => 22],
            ['id' => 345, 'name' => 'Hucal', 'province_id' => 22],
            ['id' => 346, 'name' => 'Lihuel Calel', 'province_id' => 22],
            ['id' => 347, 'name' => 'Limay Mahuida', 'province_id' => 22],
            ['id' => 348, 'name' => 'Loventué', 'province_id' => 22],
            ['id' => 349, 'name' => 'Maracó', 'province_id' => 22],
            ['id' => 350, 'name' => 'Puelén', 'province_id' => 22],
            ['id' => 351, 'name' => 'Quemú Quemú', 'province_id' => 22],
            ['id' => 352, 'name' => 'Rancul', 'province_id' => 22],
            ['id' => 353, 'name' => 'Realicó', 'province_id' => 22],
            ['id' => 354, 'name' => 'Toay', 'province_id' => 22],
            ['id' => 355, 'name' => 'Trenel', 'province_id' => 22],
            ['id' => 356, 'name' => 'Utracán', 'province_id' => 22],
            ['id' => 357, 'name' => 'Capital', 'province_id' => 13],
            ['id' => 358, 'name' => 'Castro Barros', 'province_id' => 13],
            ['id' => 359, 'name' => 'Chamical', 'province_id' => 13],
            ['id' => 360, 'name' => 'Famatina', 'province_id' => 13],
            ['id' => 361, 'name' => 'General Angel V. Peñaloza', 'province_id' => 13],
            ['id' => 362, 'name' => 'General Belgrano', 'province_id' => 13],
            ['id' => 363, 'name' => 'General Juan Facundo Quiroga', 'province_id' => 13],
            ['id' => 364, 'name' => 'General Lamadrid', 'province_id' => 13],
            ['id' => 365, 'name' => 'General Ocampo', 'province_id' => 13],
            ['id' => 366, 'name' => 'General San Martín', 'province_id' => 13],
            ['id' => 367, 'name' => 'Vinchina', 'province_id' => 13],
            ['id' => 368, 'name' => 'Independencia', 'province_id' => 13],
            ['id' => 369, 'name' => 'Rosario Vera Peñaloza', 'province_id' => 13],
            ['id' => 370, 'name' => 'Lavalle', 'province_id' => 3],
            ['id' => 371, 'name' => 'Sanagasta', 'province_id' => 13],
            ['id' => 372, 'name' => 'General Alvear', 'province_id' => 3],
            ['id' => 373, 'name' => 'Junín', 'province_id' => 3],
            ['id' => 374, 'name' => 'La Paz', 'province_id' => 3],
            ['id' => 375, 'name' => 'Malargüe', 'province_id' => 3],
            ['id' => 376, 'name' => 'San Carlos', 'province_id' => 3],
            ['id' => 377, 'name' => 'Santa Rosa', 'province_id' => 3],
            ['id' => 378, 'name' => 'Tunuyán', 'province_id' => 3],
            ['id' => 379, 'name' => 'Apóstoles', 'province_id' => 14],
            ['id' => 380, 'name' => 'Apóstoles', 'province_id' => 21],
            ['id' => 381, 'name' => 'Candelaria', 'province_id' => 14],
            ['id' => 382, 'name' => 'Capital', 'province_id' => 14],
            ['id' => 383, 'name' => 'Concepción', 'province_id' => 14],
            ['id' => 384, 'name' => 'Eldorado', 'province_id' => 14],
            ['id' => 385, 'name' => 'Guaraní', 'province_id' => 14],
            ['id' => 386, 'name' => 'General Manuel Belgrano', 'province_id' => 14],
            ['id' => 387, 'name' => 'Oberá', 'province_id' => 14],
            ['id' => 388, 'name' => 'Iguazú', 'province_id' => 14],
            ['id' => 389, 'name' => 'Leandro N. Alem', 'province_id' => 14],
            ['id' => 390, 'name' => 'Libertador General San Martín', 'province_id' => 14],
            ['id' => 391, 'name' => 'Montecarlo', 'province_id' => 14],
            ['id' => 392, 'name' => 'San Ignacio', 'province_id' => 14],
            ['id' => 393, 'name' => 'San Javier', 'province_id' => 14],
            ['id' => 394, 'name' => 'San Pedro', 'province_id' => 14],
            ['id' => 395, 'name' => '25 de Mayo', 'province_id' => 14],
            ['id' => 396, 'name' => 'Aluminé', 'province_id' => 8],
            ['id' => 397, 'name' => 'Añelo', 'province_id' => 8],
            ['id' => 398, 'name' => 'Catan Lil', 'province_id' => 8],
            ['id' => 399, 'name' => 'Los Lagos', 'province_id' => 8],
            ['id' => 400, 'name' => 'Collón Curá', 'province_id' => 8],
            ['id' => 401, 'name' => 'Confluencia', 'province_id' => 8],
            ['id' => 402, 'name' => 'Chos Malal', 'province_id' => 8],
            ['id' => 403, 'name' => 'Huiliches', 'province_id' => 8],
            ['id' => 404, 'name' => 'Chos Malal', 'province_id' => 3],
            ['id' => 405, 'name' => 'Lácar', 'province_id' => 8],
            ['id' => 406, 'name' => 'Loncopué', 'province_id' => 8],
            ['id' => 407, 'name' => 'Minas', 'province_id' => 8],
            ['id' => 408, 'name' => 'Ñorquín', 'province_id' => 8],
            ['id' => 409, 'name' => 'Picún Leufú', 'province_id' => 8],
            ['id' => 410, 'name' => 'Picunches', 'province_id' => 8],
            ['id' => 411, 'name' => 'Adolfo Alsina', 'province_id' => 15],
            ['id' => 412, 'name' => 'Avellaneda', 'province_id' => 15],
            ['id' => 413, 'name' => 'Conesa', 'province_id' => 15],
            ['id' => 414, 'name' => 'El Cuy', 'province_id' => 15],
            ['id' => 415, 'name' => 'Ñorquinco', 'province_id' => 15],
            ['id' => 416, 'name' => '9 de Julio', 'province_id' => 15],
            ['id' => 417, 'name' => 'Pichi Mahuida', 'province_id' => 15],
            ['id' => 418, 'name' => 'Pilcaniyeu', 'province_id' => 15],
            ['id' => 419, 'name' => 'San Antonio', 'province_id' => 15],
            ['id' => 420, 'name' => 'Valcheta', 'province_id' => 15],
            ['id' => 421, 'name' => '25 de Mayo', 'province_id' => 15],
            ['id' => 422, 'name' => 'Anta', 'province_id' => 9],
            ['id' => 423, 'name' => 'Cachi', 'province_id' => 9],
            ['id' => 424, 'name' => 'Cafayate', 'province_id' => 9],
            ['id' => 425, 'name' => 'Chicoana', 'province_id' => 9],
            ['id' => 426, 'name' => 'General Güemes', 'province_id' => 9],
            ['id' => 427, 'name' => 'Iruya', 'province_id' => 9],
            ['id' => 428, 'name' => 'Guachipas', 'province_id' => 9],
            ['id' => 429, 'name' => 'La Caldera', 'province_id' => 9],
            ['id' => 430, 'name' => 'La Candelaria', 'province_id' => 9],
            ['id' => 431, 'name' => 'La Viña', 'province_id' => 9],
            ['id' => 432, 'name' => 'Los Andes', 'province_id' => 9],
            ['id' => 433, 'name' => 'Metán', 'province_id' => 9],
            ['id' => 434, 'name' => 'Molinos', 'province_id' => 9],
            ['id' => 435, 'name' => 'Rivadavia', 'province_id' => 9],
            ['id' => 436, 'name' => 'Rosario de la Frontera', 'province_id' => 9],
            ['id' => 437, 'name' => 'Rosario de Lerma', 'province_id' => 9],
            ['id' => 438, 'name' => 'San Carlos', 'province_id' => 9],
            ['id' => 439, 'name' => 'Santa Victoria', 'province_id' => 9],
            ['id' => 440, 'name' => 'Albardón', 'province_id' => 18],
            ['id' => 441, 'name' => 'Calingasta', 'province_id' => 18],
            ['id' => 442, 'name' => 'Capital', 'province_id' => 18],
            ['id' => 443, 'name' => 'Chimbas', 'province_id' => 18],
            ['id' => 444, 'name' => 'Iglesia', 'province_id' => 18],
            ['id' => 445, 'name' => '9 de Julio', 'province_id' => 18],
            ['id' => 446, 'name' => 'Rivadavia', 'province_id' => 18],
            ['id' => 447, 'name' => 'San Martín', 'province_id' => 18],
            ['id' => 448, 'name' => 'Sarmiento', 'province_id' => 18],
            ['id' => 449, 'name' => 'Ullúm', 'province_id' => 18],
            ['id' => 450, 'name' => 'Valle Fértil', 'province_id' => 18],
            ['id' => 451, 'name' => 'Valle Fértil', 'province_id' => 13],
            ['id' => 452, 'name' => 'Ayacucho', 'province_id' => 17],
            ['id' => 453, 'name' => 'Ayacucho', 'province_id' => 18],
            ['id' => 454, 'name' => 'Belgrano', 'province_id' => 17],
            ['id' => 455, 'name' => 'Coronel Pringles', 'province_id' => 17],
            ['id' => 456, 'name' => 'Magallanes', 'province_id' => 23],
            ['id' => 457, 'name' => 'Chacabuco', 'province_id' => 17],
            ['id' => 458, 'name' => 'Gobernador Dupuy', 'province_id' => 17],
            ['id' => 459, 'name' => 'Junín', 'province_id' => 17],
            ['id' => 460, 'name' => 'La Capital', 'province_id' => 17],
            ['id' => 461, 'name' => 'Libertador General San Martín', 'province_id' => 17],
            ['id' => 462, 'name' => 'Corpen Aike', 'province_id' => 23],
            ['id' => 463, 'name' => 'Deseado', 'province_id' => 23],
            ['id' => 464, 'name' => 'Güer Aike', 'province_id' => 23],
            ['id' => 465, 'name' => 'Lago Argentino', 'province_id' => 23],
            ['id' => 466, 'name' => 'Lago Buenos Aires', 'province_id' => 23],
            ['id' => 467, 'name' => 'Río Chico', 'province_id' => 23],
            ['id' => 468, 'name' => 'Caseros', 'province_id' => 10],
            ['id' => 469, 'name' => 'Constitución', 'province_id' => 10],
            ['id' => 470, 'name' => 'Garay', 'province_id' => 10],
            ['id' => 471, 'name' => 'General López', 'province_id' => 10],
            ['id' => 472, 'name' => 'Iriondo', 'province_id' => 10],
            ['id' => 473, 'name' => 'General Obligado', 'province_id' => 10],
            ['id' => 474, 'name' => 'Las Colonias', 'province_id' => 10],
            ['id' => 475, 'name' => '9 de Julio', 'province_id' => 10],
            ['id' => 476, 'name' => 'Rosario', 'province_id' => 10],
            ['id' => 477, 'name' => 'San Cristóbal', 'province_id' => 10],
            ['id' => 478, 'name' => 'San Cristóbal', 'province_id' => 20],
            ['id' => 479, 'name' => 'San Javier', 'province_id' => 10],
            ['id' => 480, 'name' => 'San Jerónimo', 'province_id' => 10],
            ['id' => 481, 'name' => 'San Justo', 'province_id' => 10],
            ['id' => 482, 'name' => 'San Lorenzo', 'province_id' => 10],
            ['id' => 483, 'name' => 'San Martín', 'province_id' => 10],
            ['id' => 484, 'name' => 'Vera', 'province_id' => 10],
            ['id' => 485, 'name' => 'Aguirre', 'province_id' => 20],
            ['id' => 486, 'name' => 'Alberdi', 'province_id' => 20],
            ['id' => 487, 'name' => 'Burruyacú', 'province_id' => 16],
            ['id' => 488, 'name' => 'Atamisqui', 'province_id' => 20],
            ['id' => 489, 'name' => 'Avellaneda', 'province_id' => 20],
            ['id' => 490, 'name' => 'Banda', 'province_id' => 20],
            ['id' => 491, 'name' => 'Belgrano', 'province_id' => 20],
            ['id' => 492, 'name' => 'Capital', 'province_id' => 20],
            ['id' => 493, 'name' => 'Copo', 'province_id' => 20],
            ['id' => 494, 'name' => 'Graneros', 'province_id' => 16],
            ['id' => 495, 'name' => 'Choya', 'province_id' => 20],
            ['id' => 496, 'name' => 'Figueroa', 'province_id' => 20],
            ['id' => 497, 'name' => 'General Taboada', 'province_id' => 20],
            ['id' => 498, 'name' => 'Guasayán', 'province_id' => 20],
            ['id' => 499, 'name' => 'Guasayán', 'province_id' => 11],
            ['id' => 500, 'name' => 'Jiménez', 'province_id' => 20],
            ['id' => 501, 'name' => 'Juan Felipe Ibarra', 'province_id' => 20],
            ['id' => 502, 'name' => 'Loreto', 'province_id' => 20],
            ['id' => 503, 'name' => 'Mitre', 'province_id' => 20],
            ['id' => 504, 'name' => 'Moreno', 'province_id' => 20],
            ['id' => 505, 'name' => 'Ojo de Agua', 'province_id' => 20],
            ['id' => 506, 'name' => 'Pellegrini', 'province_id' => 20],
            ['id' => 507, 'name' => 'Quebrachos', 'province_id' => 20],
            ['id' => 508, 'name' => 'Robles', 'province_id' => 20],
            ['id' => 509, 'name' => 'Río Hondo', 'province_id' => 20],
            ['id' => 510, 'name' => 'Chicligasta', 'province_id' => 16],
            ['id' => 511, 'name' => 'Rivadavia', 'province_id' => 20],
            ['id' => 512, 'name' => 'Salavina', 'province_id' => 20],
            ['id' => 513, 'name' => 'San Martín', 'province_id' => 20],
            ['id' => 514, 'name' => 'Sarmiento', 'province_id' => 20],
            ['id' => 515, 'name' => 'Silípica', 'province_id' => 20],
            ['id' => 516, 'name' => 'Graneros', 'province_id' => 20],
            ['id' => 517, 'name' => 'Juan Bautista Alberdi', 'province_id' => 16],
            ['id' => 518, 'name' => 'La Cocha', 'province_id' => 16],
            ['id' => 519, 'name' => 'Leales', 'province_id' => 16],
            ['id' => 520, 'name' => 'Leales', 'province_id' => 20],
            ['id' => 521, 'name' => 'Monteros', 'province_id' => 16],
            ['id' => 522, 'name' => 'Capital', 'province_id' => 16],
            ['id' => 523, 'name' => 'Simoca', 'province_id' => 16],
            ['id' => 524, 'name' => 'Tafí del Valle', 'province_id' => 16],
            ['id' => 525, 'name' => 'Tafí Viejo', 'province_id' => 16],
            ['id' => 526, 'name' => 'Trancas', 'province_id' => 16],
            ['id' => 527, 'name' => 'Río Grande', 'province_id' => 19],
            ['id' => 528, 'name' => 'Ushuaia', 'province_id' => 19],
            ['id' => 529, 'name' => 'Ciudad de Buenos Aires', 'province_id' => 24],
            ['id' => 530, 'name' => 'Comuna 11', 'province_id' => 25],
            ['id' => 531, 'name' => 'null', 'province_id' => 25],
            ['id' => 532, 'name' => 'Comuna 1', 'province_id' => 25],
            ['id' => 533, 'name' => 'Comuna 10', 'province_id' => 25],
            ['id' => 534, 'name' => 'Santa Fe', 'province_id' => 26],
            ['id' => 535, 'name' => 'Comuna 14', 'province_id' => 25],
            ['id' => 536, 'name' => 'Comuna 7', 'province_id' => 25],
            ['id' => 537, 'name' => 'Buenos Aires', 'province_id' => 27],
            ['id' => 538, 'name' => 'Comuna 3', 'province_id' => 25],
            ['id' => 539, 'name' => 'Comuna 9', 'province_id' => 25],
            ['id' => 540, 'name' => 'Comuna 4', 'province_id' => 25],
            ['id' => 541, 'name' => 'Pilar Centro', 'province_id' => 29],
            ['id' => 542, 'name' => 'Comuna 12', 'province_id' => 25],
            ['id' => 543, 'name' => 'Comuna 15', 'province_id' => 25],
            ['id' => 544, 'name' => 'Comuna 8', 'province_id' => 25],
            ['id' => 545, 'name' => 'Comuna 6', 'province_id' => 25],
            ['id' => 546, 'name' => 'ACD', 'province_id' => 31],
            ['id' => 547, 'name' => 'Comuna 13', 'province_id' => 30],
        ];

        DB::table('cities')->upsert($cities, ['id'], ['name', 'province_id']);
    }
}
